package domuscontrol.suggestions;

import java.util.Objects;

import domuscontrol.routines.Automation;

/**
 * Represents an automation suggestion generated from past user interactions.
 * Each suggestion contains a description and the automation that can be added if accepted.
 * Suggestions are generated by analyzing patterns in interaction logs.
 * 
 * @author Afonso Barros (a112178)
 * @author Martim Monteiro (a111013)
 * @author Matheus Azevedo (a111430)
 * @version 1.0
 */
public class AutomationSuggestion {

    /** Human-readable explanation of why this suggestion was generated. */
    private String description;

    /** The pre-built Automation object ready to be added if the user accepts. */
    private Automation automation;

    /**
     * Creates an empty automation suggestion.
     */
    public AutomationSuggestion() {
        this.description = "";
        this.automation = null;
    }

    /**
     * Creates an automation suggestion with the given description and automation.
     * The provided automation is copied before being stored.
     *
     * @param description the suggestion description
     * @param automation the automation to suggest
     */
    public AutomationSuggestion(String description, Automation automation) {
        this.description = description;
        this.automation = automation != null ? automation.clone() : null;
    }

    /**
     * Creates a copy of another automation suggestion.
     *
     * @param other the suggestion to copy
     */
    public AutomationSuggestion(AutomationSuggestion other) {
        this.description = other.getDescription();
        this.automation = other.getAutomation();
    }

    /**
     * Gets the suggestion description.
     *
     * @return the suggestion description
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets the description of this suggestion.
     *
     * @param description the suggestion description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets a copy of the suggested automation.
     *
     * @return a copied automation, or null if not set
     */
    public Automation getAutomation() {
        return this.automation != null ? this.automation.clone() : null;
    }

    /**
     * Sets the pre-built Automation for this suggestion.
     * The provided automation is copied before being stored.
     *
     * @param automation the automation to store
     */
    public void setAutomation(Automation automation) {
        this.automation = automation != null ? automation.clone() : null;
    }

    /**
     * Creates a copy of this suggestion.
     *
     * @return a copied AutomationSuggestion instance
     */
    @Override
    public AutomationSuggestion clone() {
        return new AutomationSuggestion(this);
    }

    /**
     * Compares this suggestion with another object for equality.
     *
     * @param o the object to compare with
     * @return true if description and automation match; false otherwise.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || this.getClass() != o.getClass()) return false;
        AutomationSuggestion suggestion = (AutomationSuggestion) o;
        return Objects.equals(this.getDescription(), suggestion.getDescription()) &&
               Objects.equals(this.getAutomation(), suggestion.getAutomation());
    }

    /**
     * Generates a hash code for this suggestion.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {
        return Objects.hash(this.getDescription(), this.getAutomation());
    }

    /**
     * Returns a string representation of this suggestion.
     *
     * @return a formatted string with the suggestion information
     */
    @Override
    public String toString() {
        Automation a = this.getAutomation();
        StringBuilder sb = new StringBuilder();
        sb.append("AutomationSuggestion { ")
          .append("Description: '").append(this.getDescription()).append('\'')
          .append(", Automation: ").append(a != null ? a.getName() : "null")
          .append(" }");
        return sb.toString();
    }
}
