package domuscontrol.suggestions;

import java.util.Objects;

import domuscontrol.routines.Automation;

/**
 * Represents a suggested automation generated by the SuggestionEngine
 * based on detected patterns in the house's interaction history.
 * Contains a human-readable description and the pre-built Automation
 * ready to be added to the RoutineManager if accepted.
 */
public class AutomationSuggestion {

    /** Human-readable explanation of why this suggestion was generated. */
    private String description;

    /** The pre-built Automation object ready to be added if the user accepts. */
    private Automation automation;

    /**
     * Default constructor initializing all fields to safe defaults.
     */
    public AutomationSuggestion() {
        this.description = "";
        this.automation  = null;
    }

    /**
     * Parameterized constructor.
     *
     * @param description A human-readable description of the suggestion.
     * @param automation  The pre-built Automation to add if accepted.
     */
    public AutomationSuggestion(String description, Automation automation) {
        this.description = description;
        this.automation  = automation != null ? automation.clone() : null;
    }

    /**
     * Copy constructor using getters to access the other instance's state.
     *
     * @param other The existing AutomationSuggestion instance to copy.
     */
    public AutomationSuggestion(AutomationSuggestion other) {
        this.description = other.getDescription();
        this.automation  = other.getAutomation();
    }

    /**
     * Returns the human-readable description of this suggestion.
     *
     * @return The description string.
     */
    public String getDescription() { return description; }

    /**
     * Sets the description of this suggestion.
     *
     * @param description The new description string.
     */
    public void setDescription(String description) { this.description = description; }

    /**
     * Returns a clone of the pre-built Automation object.
     *
     * @return A clone of the Automation, or null if not set.
     */
    public Automation getAutomation() {
        return this.automation != null ? this.automation.clone() : null;
    }

    /**
     * Sets the pre-built Automation for this suggestion.
     *
     * @param automation The Automation to store (deep copied).
     */
    public void setAutomation(Automation automation) {
        this.automation = automation != null ? automation.clone() : null;
    }

    /**
     * Creates a deep copy of this suggestion.
     *
     * @return A new AutomationSuggestion instance.
     */
    @Override
    public AutomationSuggestion clone() {
        return new AutomationSuggestion(this);
    }

    /**
     * Compares this suggestion with another object for equality using getters.
     *
     * @param o The object to compare with.
     * @return true if description and automation match; false otherwise.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || this.getClass() != o.getClass()) return false;
        AutomationSuggestion that = (AutomationSuggestion) o;
        return Objects.equals(this.getDescription(), that.getDescription()) &&
               Objects.equals(this.getAutomation(), that.getAutomation());
    }

    /**
     * Generates a hash code for this suggestion.
     *
     * @return The hash code based on description and automation.
     */
    @Override
    public int hashCode() {
        return Objects.hash(this.getDescription(), this.getAutomation());
    }

    /**
     * Returns a string representation of this suggestion.
     *
     * @return Formatted string with description and automation name.
     */
    @Override
    public String toString() {
        Automation a = this.getAutomation();
        return "AutomationSuggestion { description=\"" + this.getDescription() +
               "\", automation=" + (a != null ? a.getName() : "null") + " }";
    }
}